package token;

public enum TokenType {
  STRING_TYPE, STRING, NUMBER_TYPE, INTEGER, FLOATING_POINT, ASSIGNATION, IDENTIFIER, COLON, SEMICOLON, LET, ADDITION, SUBSTRACTION, MULTIPLICATION, DIVISION, PRINTLN,
  // PRINTSCRIPT 1.1
  CONST, BOOLEAN_TYPE, TRUE, FALSE, GREATER, SMALLER, EQUAL_OR_G, EQUAL_OR_S, IF, ELSE, OPENING_PARENTHESIS, CLOSING_PARENTHESIS, OPENING_BRACKETS, CLOSING_BRACKETS
}
