# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
    - name: Google Java Format
  # You may pin to the exact commit or the version.
  # uses: axel-op/googlejavaformat-action@5045c8c244a22eb6a28eeb6050cc2baebd75c5f2
      uses: axel-op/googlejavaformat-action@v3.4.0
      with:
    # Arguments for the Google Java Format executable
        args: --replace
    # Set to true to not commit the changes
        skipCommit: false
 
    # Recommended on MacOS machines
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
